from flask import Flask
app = Flask(__name__)

import application.view

# For stress testing
import application.stress

from application.models import theDB
# This hook ensures that a connection is opened to handle any queries
# generated by the request.
@app.before_request
def _db_connect():
    theDB.connect()

# This hook ensures that the connection is closed when we've finished
# processing the request.
@app.teardown_appcontext
def _db_close(exc):
    if not theDB.is_closed():
        theDB.close()