# CONFIGURATION
# Top-level keys are categorical; where possible, introduce
# new top-level keys to keep constants/ideas separate.
# Note that we parse this with the configuration library,
# which has some fancy extensions to allow referencing between
# different elements in the YAML file.
# See http://configure.readthedocs.io/en/latest/#
application:
  title: "The Template App"

databases:
  mess:
    filename: data/mess.sqlite
  roles:
    filename: data/roles.sqlite

sys:
  debug: True
  host: "0.0.0.0"
  port: 5000

flask:
  # Secret key for signing cookies
  secretKey: "secret"

controllers: !include:controllers.yaml