#!/bin/bash

if [ "$#" -ne 1 ]; then
  echo
  echo "Include the name of the page you want to create."
  echo "For example:"
  echo "create-page handleLogin"
  echo
  echo "The 'controller' and 'template' extensions will be added automatically."
fi

# FIXME: Strip out the .py if they add it.
newController=${1}Controller.py
if [ ! -f application/controllers/${newController} ]; then
  cp  application/controllers/defaultController.txt \
      application/controllers/${newController}
else
  echo "Controller already exists: ${newController}"
fi

exit 0
