inputs:
  - title: "Chemical Name"
    id: "chemId" # This may need to change
    type: "text"
    autoPop: "true"
    var: "setChem"
  - title: "Previous Location"
    id: "prevStorageId" #This should change to whatever will get the full location information
    type: "text"
    autoPop: "true"
    var: "setLoc"
  - title: "Previous Quantity"
    id: "prevQuantity" # This should change to whatever will get the full quantity info
    type: "text"
    autoPop: "true"
    var: "setQuantity"
  - title: "Current Location" #This may be unclear... maybe 'New Location'
    id: "storageId" # This may need to change
    type: "text"
    special: "required"
  - title: "Current Quantity"
    id: "currentQuantity" # This may also need to change
    type: "number"
    special: "required"
  - title: "Current Unit"
    id: "currentQuantityUnit"
    type: "select"
    options:
      - "gram (g)"
      - "ounce (oz)"
      - "pound (lb)"
      - "liter (L)"
      - "milliliter (mL)"
      - "gallon (gal)"
    special: "required"