# Add Chemical form
pictograms:
  # Pictograms found @ https://www.osha.gov/dsg/hazcom/pictograms/
    - title: "corrosive"
      pict: "/static/pictograms/corrosivePict.png"
      alt: "Corrosion"
    - title: "environmental"
      pict: "/static/pictograms/environmentalPict.png"
      alt: "Environmental"
    - title: "exclamation"
      pict: "/static/pictograms/exclamationPict.png"
      alt: "Exclamation Mark"
    - title: "flame"
      pict: "/static/pictograms/flamePict.png"
      alt: "Flame"
    - title: "gasCylinder"
      pict: "/static/pictograms/gasCylinderPict.png"
      alt: "Gas Cylinder"
    - title: "health"
      pict: "/static/pictograms/healthPict.png"
      alt: "Health Hazard"
    - title: "oxidizer"
      pict: "/static/pictograms/oxidizerPict.png"
      alt: "Flame Over Circle"
    - title: "toxic"
      pict: "/static/pictograms/toxicPict.png"
      alt: "Skull and Crossbones"

NFPAdiamond:
  # Used to build the selection form for the NFPA "Fire Diamond"
    - section: "Health"
      id: "healthHazard"
      selections: 
       - "0"
       - "1"
       - "2"
       - "3"
       - "4"
    - section: "Flammability"
      id: "flammable"
      selections: 
       - "0"
       - "1"
       - "2"
       - "3"
       - "4"
    - section: "Instability/Reactivity"
      id: "reactive"
      selections: 
       - "0"
       - "1"
       - "2"
       - "3"
       - "4"
    - section: "Special"
      id: "other"
      selections: 
       - "None"
       - "OX (Oxidizer)"
       - "₩ (Water Reactive)"
       - "SA (Simple Asphyxiant Gas)"
       
addChemInputs:
    - name: "Name"
      id: "name"
      type: "text"
      placeholder: "Chemical Name"
    - name: "Cas Number"
      id: "casNum"
      type: "text"
      placeholder: "Cas Number"
    - name: "Formula"
      id: "formula"
      type: "text"
      placeholder: "Chemical Formula"
    - name: "Concentration"
      id: "concentration"
      type: "number"
      placeholder: "Percent Concentration"
      addon: "Percent Sign"
    - name: "Flash Point"
      id: "flashPoint"
      type: "number"
      placeholder: "Degrees Fahrenheit"
      small: "In Fahrenheit"
    - name: "Boiling Point"
      id: "boilPoint"
      type: "number"
      placeholder: "Degrees Fahrenheit"
      small: "In Fahrenheit"
    - name: "Storage Temp"
      id: "storageTemp"
      type: "number"
      placeholder: "Degrees Fahrenheit"
      small: "In Fahrenheit"
    - name: "Safety Data Sheet Link"
      id: "sdsLink"
      type: "text"
      placeholder: "SDS Link"
    - name: "Description"
      id: "description"
      type: "textarea"
      placeholder: "Description of Chemical"

addChemChecks:
    - name: "Pressure Former"
      id: "pressureFormer"
    - name: "Peroxide Former"
      id: "peroxideFormer"
       
addChemDropdowns:
    - name: "Primary Hazard"
      id: "primaryHazard"
      selections:
        - "Flammable"
          # color: "Red"
        - "Flammable Solid"
          # color: "Copper"
        - "Organic Health Hazard"
          # color: "Blue"
        - "Inorganic Health Hazard"
          # color: "Blue"
        - "Organic Acid"
          # color: "Lavender"
        - "Inorganic Acid"
          # color: "Rose"
        - "Base"
          # color: "Green"
        - "Oxidizer"
          # color: "Yellow"
        - "Reactive"
          # color: "Orange"
    - name: "Structure"
      id: "structure"
      selections:
        - "Organic"
        - "Inorganic"
    - name: "State"
      id: "state"
      selections:
        - "Solid"
        - "Liquid"
        - "Gas"
