# CONFIGURATION
# Top-level keys are categorical; where possible, introduce
# new top-level keys to keep constants/ideas separate.
# Note that we parse this with the configuration library,
# which has some fancy extensions to allow referencing between
# different elements in the YAML file.
# See http://configure.readthedocs.io/en/latest/#
application:
  title: "Berea Chemical Inventory System"
  default: index

databases:
  roles:
    filename: data/roles.sqlite
  inventory:
    filename: data/inventory.sqlite

sys:
  debug: True
  host: "0.0.0.0"
  port: 8080

hazards:
    Base: Green   #Does Base need to be in quotes?
    "Flammable": Red
    "Flammable Solid": Copper
    "Health Hazard": Blue
    Inorganic Acid: Rose  #Does Inorganic Acid need to be in quotes?
    "Organic Acid": Lavender
    "Oxidizer": Yellow
    "Reactive": Orange
    
maMenu:
  - title: "Home"
    link: "/ma/adminHome/"
  - title: "View Chemical Table"
    link: "/ma/ChemTable/"
  - title: "Check In a Container"
    link: "/ma/CheckIn/"
  - title: "Add a Chemical"
    link: "/ma/AddChemical/"
  - title: "Manage Users"
    link: "/ma/ViewUser/"

faMenu:
  - title: "Home"
    link: "/fa/Home/"
  - title: "View Chemical Table"
    link: "/fa/ChemTable"
  - title: "Request Access For a Student"
    link: "/fa/RequestUserAccess/"
    
aMenu:
  - title: "Home"
    link: "a/ChemTable"

saMenu:
  - title: "System Admin Home"
    link: "/sa/SystemAdminHome/"
  - title: "View Chemical Table"
    link: "/sa/ChemTable/"
  - title: "Check In"
    link: "/sa/CheckIn/"
  - title: "Add Chemical"
    link: "/sa/AddChemical/"
  
  
  
flask:
  # Secret key for signing cookies
  # Only needed for admin module, and we don't seem to rely on
  # it. Hence, we will randomly generate a key.
  secretKey: RANDOM

controllers: !include:controllers.yaml