# CONFIGURATION
# Top-level keys are categorical; where possible, introduce
# new top-level keys to keep constants/ideas separate.
# Note that we parse this with the configuration library,
# which has some fancy extensions to allow referencing between
# different elements in the YAML file.
# See http://configure.readthedocs.io/en/latest/#
application:
  title: "Berea Chemical Inventory System"
  default: index

databases:
  roles:
    filename: data/roles.sqlite
  inventory:
    filename: data/inventory.sqlite

sys:
  debug: True
  host: "0.0.0.0"
  port: 8080
  
# Add Chemical form
pictograms:
  # Pictograms found @ https://www.osha.gov/dsg/hazcom/pictograms/
    - title: "corrosive"
      pict: "/static/pictograms/corrosivePict.jpg"
      alt: "Corrosion"
    - title: "environmental"
      pict: "/static/pictograms/environmentalPict.jpg"
      alt: "Environmental"
    - title: "exclamation"
      pict: "/static/pictograms/exclamationPict.jpg"
      alt: "Exclamation Mark"
    - title: "flammable"
      pict: "/static/pictograms/flammablePict.jpg"
      alt: "Flame"
    - title: "gasCylinder"
      pict: "/static/pictograms/gasCylinderPict.jpg"
      alt: "Gas Cylinder"
    - title: "health"
      pict: "/static/pictograms/healthPict.jpg"
      alt: "Health Hazard"
    - title: "oxidizer"
      pict: "/static/pictograms/oxidizerPict.jpg"
      alt: "Flame Over Circle"
    - title: "toxic"
      pict: "/static/pictograms/toxicPict.jpg"
      alt: "Skull and Crossbones"

NFPAdiamond:
  # Used to build the selection form for the NFPA "Fire Diamond"
    - section: "Health"
      id: "healthHazard"
      selections: 
       - "0"
       - "1"
       - "2"
       - "3"
       - "4"
    - section: "Flammability"
      id: "flammable"
      selections: 
       - "0"
       - "1"
       - "2"
       - "3"
       - "4"
    - section: "Instability/Reactivity"
      id: "reactive"
      selections: 
       - "0"
       - "1"
       - "2"
       - "3"
       - "4"
    - section: "Special"
      id: "other"
      selections: 
       - "None"
       - "OX (Oxidizer)"
       - "₩ (Water Reactive)"
       - "SA (Simple Asphyxiant Gas)"
       
addChemInputs:
    - name: "Name"
      id: "name"
      type: "text"
      placeholder: "Chemical Name"
    - name: "Cas Number"
      id: "casNum"
      type: "text"
      placeholder: "Cas Number"
    - name: "Formula"
      id: "formula"
      type: "text"
      placeholder: "Chemical Formula"
    - name: "Concentration"
      id: "concentration"
      type: "number"
      placeholder: "Percent Concentration"
      addon: "Percent Sign"
    - name: "Flash Point"
      id: "flashPoint"
      type: "number"
      placeholder: "Degrees Fahrenheit"
      small: "In Fahrenheit"
    - name: "Boiling Point"
      id: "boilPoint"
      type: "number"
      placeholder: "Degrees Fahrenheit"
      small: "In Fahrenheit"
    - name: "Storage Temp"
      id: "storageTemp"
      type: "number"
      placeholder: "Degrees Fahrenheit"
      small: "In Fahrenheit"
    - name: "Safety Data Sheet Link"
      id: "sdsLink"
      type: "text"
      placeholder: "SDS Link"
    - name: "Description"
      id: "description"
      type: "textarea"
      placeholder: "Description of Chemical"
       
addChemDropdowns:
    - name: "Primary Hazard"
      id: "primaryHazard"
      selections:
        - "Flammable"
          # color: "Red"
        - "Flammable Solid"
          # color: "Copper"
        - "Organic Health Hazard"
          # color: "Blue"
        - "Inorganic Health Hazard"
          # color: "Blue"
        - "Organic Acid"
          # color: "Lavender"
        - "Inorganic Acid"
          # color: "Rose"
        - "Base"
          # color: "Green"
        - "Oxidizer"
          # color: "Yellow"
        - "Reactive"
          # color: "Orange"
    - name: "Structure"
      id: "structure"
      selections:
        - "Organic"
        - "Inorganic"
    - name: "State"
      id: "state"
      selections:
        - "Solid"
        - "Liquid"
        - "Gas"

# Color Codes
hazards:
    - hazard: "Base"
      color: "Green"   
    - hazard: "Flammable"
      color: "Red"
    - hazard: "Flammable Solid"
      color: "Copper"
    - hazard: "Health"
      color: "Blue"
    - hazard: "Inorganic Acid"
      color: "Rose"
    - hazard: "Organic Acid"
      color: "Lavender"
    - hazard: "Oxidizer"
      color: "Yellow"
    - hazard: "Reactive"
      color: "Orange"
 
# Navigation bars   
maMenu:
  - title: "Home"
    link: "/ma/Home/"
  - title: "View Chemical Table"
    link: "/ma/ChemTable/"
  - title: "Check In a Container"
    link: "/ma/CheckIn/"
  - title: "Add a Chemical"
    link: "/ma/AddChemical/"
  - title: "Manage Users"
    link: "/ma/ViewUser/"

faMenu:
  - title: "Home"
    link: "/fa/Home/"
  - title: "View Chemical Table"
    link: "/fa/ChemTable/"
  - title: "Request Access For a Student"
    link: "/fa/RequestUserAccess/"
    
aMenu:
  - title: "Home"
    link: "/a/ChemTable/"

saMenu:
  - title: "Home"
    link: "/sa/Home/"
  - title: "View Chemical Table"
    link: "/sa/ChemTable/"
  - title: "Check In"
    link: "/sa/CheckIn/"
  - title: "Add Chemical"
    link: "/sa/AddChemical/"
  
  
  
flask:
  # Secret key for signing cookies
  # Only needed for admin module, and we don't seem to rely on
  # it. Hence, we will randomly generate a key.
  secretKey: RANDOM

controllers: !include:controllers.yaml