# CONFIGURATION
# Top-level keys are categorical; where possible, introduce
# new top-level keys to keep constants/ideas separate.
# Note that we parse this with the configuration library,
# which has some fancy extensions to allow referencing between
# different elements in the YAML file.
# See http://configure.readthedocs.io/en/latest/#
application:
  title: "Berea Chemical Inventory System"
  default: index

databases:
  roles:
    filename: data/roles.sqlite
  inventory:
    filename: data/inventory.sqlite

sys:
  debug: True
  host: "0.0.0.0"
  port: 8080

pictograms:
  # Pictograms found @ https://www.osha.gov/dsg/hazcom/pictograms/
    - title: "corrosive"
      pict: "/static/pictograms/corrosivePict.jpg"
      alt: "Corrosion"
    - title: "environmental"
      pict: "/static/pictograms/environmentalPict.jpg"
      alt: "Environmental"
    - title: "exclamation"
      pict: "/static/pictograms/exclamationPict.jpg"
      alt: "Exclamation Mark"
    - title: "flammable"
      pict: "/static/pictograms/flammablePict.jpg"
      alt: "Flame"
    - title: "gasCylinder"
      pict: "/static/pictograms/gasCylinderPict.jpg"
      alt: "Gas Cylinder"
    - title: "health"
      pict: "/static/pictograms/healthPict.jpg"
      alt: "Health Hazard"
    - title: "oxidizer"
      pict: "/static/pictograms/oxidizerPict.jpg"
      alt: "Flame Over Circle"
    - title: "toxic"
      pict: "/static/pictograms/toxicPict.jpg"
      alt: "Skull and Crossbones"

NFPAdiamond:
    - section: "Health"
      selections: 
       - "0"
       - "1"
       - "2"
       - "3"
       - "4"
    - section: "Flammability"
      selections: 
       - "0"
       - "1"
       - "2"
       - "3"
       - "4"
    - section: "Instability"
      selections: 
       - "0"
       - "1"
       - "2"
       - "3"
       - "4"
    - section: "Special"
      selections: 
       - "OX (Oxidizer)"
       - "₩ (Water Reactive)"
       - "SA (Simple Asphyxiant Gas)"

hazards:
    - hazard: "Base"
      color: "Green"   
    - hazard: "Flammable"
      color: "Red"
    - hazard: "Flammable Solid"
      color: "Copper"
    - hazard: "Health"
      color: "Blue"
    - hazard: "Inorganic Acid"
      color: "Rose"
    - hazard: "Organic Acid"
      color: "Lavender"
    - hazard: "Oxidizer"
      color: "Yellow"
    - hazard: "Reactive"
      color: "Orange"
    
maMenu:
  - title: "Home"
    link: "/ma/Home/"
  - title: "View Chemical Table"
    link: "/ma/ChemTable/"
  - title: "Check In a Container"
    link: "/ma/CheckIn/"
  - title: "Add a Chemical"
    link: "/ma/AddChemical/"
  - title: "Manage Users"
    link: "/ma/ViewUser/"

faMenu:
  - title: "Home"
    link: "/fa/Home/"
  - title: "View Chemical Table"
    link: "/fa/ChemTable/"
  - title: "Request Access For a Student"
    link: "/fa/RequestUserAccess/"
    
aMenu:
  - title: "Home"
    link: "/a/ChemTable/"

saMenu:
  - title: "Home"
    link: "/sa/Home/"
  - title: "View Chemical Table"
    link: "/sa/ChemTable/"
  - title: "Check In"
    link: "/sa/CheckIn/"
  - title: "Add Chemical"
    link: "/sa/AddChemical/"
  
  
  
flask:
  # Secret key for signing cookies
  # Only needed for admin module, and we don't seem to rely on
  # it. Hence, we will randomly generate a key.
  secretKey: RANDOM

controllers: !include:controllers.yaml