# CONFIGURATION
# Top-level keys are categorical; where possible, introduce
# new top-level keys to keep constants/ideas separate.
# Note that we parse this with the configuration library,
# which has some fancy extensions to allow referencing between
# different elements in the YAML file.
# See http://configure.readthedocs.io/en/latest/#
application:
  title: "Berea Chemical Inventory System"
  default: index

databases:
  roles:
    filename: data/roles.sqlite
  inventory:
    filename: data/inventory.sqlite

sys:
  debug: True
  host: "0.0.0.0"
  port: 8080

# Color Codes
hazards:
  "Base": 
    hazardColor: "Green"
    textColor: "#FFFFFF"
    hexColor: "#329032"
  "Flammable":
    hazardColor: "Red"
    textColor: "#FFFFFF"
    hexColor: "#FF0000"
  "Flammable Solid":
    hazardColor: "Copper"
    textColor: "White"
    hexColor: "#B87333"
  "Organic Health Hazard":
    hazardColor: "Blue"
    textColor: "#FFFFFF"
    hexColor: "#0000FF"
  "Inorganic Health Hazard":
    hazardColor: "Blue"
    textColor: "#FFFFFF"
    hexColor: "#0000FF"
  "Inorganic Acid":
    hazardColor: "Rose"
    textColor: "#333333"
    hexColor: "#FFE4E1"
  "Organic Acid":
    hazardColor: "Lavender"
    textColor: "#333333"
    hexColor: "#E6E6FA"
  "Oxidizer":
    hazardColor: "Yellow"
    textColor: "#333333"
    hexColor: "#FFFF00"
  "Reactive":
    hazardColor: "Orange"
    textColor: "#FFFFFF"
    hexColor: "#FFA500"
 
# Navigation bars   
maMenu:
  - title: "Home"
    link: " /ma/Home/"
  - title: "View All Chemicals"
    link: "/ma/ChemTable/"

faMenu:
  - title: "View All Chemicals"
    link: "/fa/ChemTable/"
  - title: "Request Access For a Student"
    link: "/fa/RequestUserAccess/"
    
aMenu:
  - title: "Home"
    link: "/a/ChemTable/"

saMenu:
  - title: "Home"
    link: "/sa/Home/"
  - title: "View All Chemicals"
    link: "/sa/ChemTable/"

  
  
  
flask:
  # Secret key for signing cookies
  # Only needed for admin module, and we don't seem to rely on
  # it. Hence, we will randomly generate a key.
  secretKey: RANDOM

controllers: !include:controllers.yaml

DEBUG:
  user: "ballz" #admin