layout:
  - directory:
      name: stu
      controllers:
        - name: students
          handlers:
          - purpose: "Collect the user's happiness."
            route: "/stu/happy"
            methods: 
              - GET
            function: stuHappy
            roles: 
              - students
          - purpose: "Find out how sad they are."
            route: "/stu/sad/<int:sadness>"
            methods:
              - GET
              - POST
            function: stuSad
            roles: 
              - students
  - directory:
      name: fac
      controllers:
        - name: faculty
          handlers:
          - purpose: "Collect the user's happiness."
            route: "/fac/happy"
            methods: 
              - GET
            function: facHappy
            roles: 
              - students
          - purpose: "Find out how sad they are."
            route: "/fac/sad/<int:sadness>"
            methods:
              - GET
              - POST
            function: facSad
            roles: 
              - students
