layout:
  - directory:
      name: stu
      controllers:
        - name: hello
          handlers:
          - purpose: "Collect the user's happiness."
            route: "/stu/happy"
            methods: 
              - GET
            function: happyHappy
            roles: 
              - students
          - purpose: "Find out how sad they are."
            route: /stu/sad/<int:sadness>"
            methods:
              - GET
              - POST
            function: sadSad
            roles: 
              - students
  - directory:
      name: fac
      controllers:
        - name: hello
          handlers:
          - purpose: "Collect the user's happiness."
            route: "/fac/happy"
            methods: 
              - GET
            function: happyHappy
            roles: 
              - students
          - purpose: "Find out how sad they are."
            route: /fac/sad/<int:sadness>"
            methods:
              - GET
              - POST
            function: sadSad
            roles: 
              - students
