containerInformation:
    - name: "Room"
      id: "storageId"
      type: "select"
      options: "roomsList"
      special: "required"
    - name: "Container Type"
      id: "conType"
      type: "text"
      placeholder: "Container Type"
      special: "required"
    - name: "Container Capacity"
      id: "capacity"
      type: "number"
      placeholder: "Container Capacity"
      special: "required"
    - name: "Container Unit"
      id: "capacityUnit"
      type: "select"
      options: &units
      # I'm not entirely sure if this is the best way to do this
        - "gram (g)"
        - "ounce (oz)"
        - "pound (lb)"
        - "liter (L)"
        - "milliliter (mL)"
        - "gallon (gal)"
      special: "required"
    - name: "Current Quantity"
      id: "currentQuantity"
      type: "number"
      placeholder: "Current Quantity"
      special: "required"
    - name: "Current Unit"
      id: "currentQuantityUnit"
      type: "select"
      options: *units
      special: "required"
    - name: "Manufacturer"
      id: "manufacturer"
      type: "text"
      placeholder: "Manufacturer"
      special: "required"
    - name: "Barcode"
      id: "barcodeId"
      type: "text"
      special: "readonly"