layout:
  - directory:
    name: a # All
    controllers:
      - name: aChemTable
        handlers:
          # Chemical table controller
          - purpose: "Shows all Chemicals in Database."
            route: "/a/ChemTable/"
            methods:
              - GET
            function: aChemTable
            roles:
              - systemUser
              
      - name: aViewChemical
        handlers:
        # Chemical page controller
          - purpose: "Shows specific chemical and all containers of said chemical."
            route: "/a/ViewChemical/<string:chemical>/"
            methods:
              - GET
            function: aViewChemical
            roles:
              - systemUser
              
################################################################################

  - directory:
    name: fa # superUser
    controllers:
      - name: RequestUserAccess
        handlers:
          - purpose: "superUser or Staff requesting for a student to have access to the system."
            route: "/fa/RequestUserAccess/"
            methods:
              - GET
            function: RequestUserAccess
            roles:
              - superUser
              
      - name: faChemTable
        handlers:
          # Chemical table controller
          - purpose: "Shows all Chemicals in Database."
            route: "/fa/ChemTable/"
            methods:
              - GET
            function: faChemTable
            roles:
              - superUser
              
      - name: faViewChemical
        handlers:
        # Chemical page controller
          - purpose: "Shows specific chemical and all containers of said chemical."
            route: "/fa/ViewChemical/<string:chemical>/"
            methods:
              - GET
            function: faViewChemical
            roles:
              - superUser
              
      - name: Home
        handlers:
            - purpose: "This is the homepage/dashboard for the professor"
              route: "/fa/Home/"
              methods:
                - GET
              function: Home
              roles:
                - superUser
                
################################################################################
              
  - directory:
    name: sa #EHS staff
    controllers:
      - name: SystemAdminHome
        handlers:
          - purpose: "Home page and dash boeard for EHS staff/system admins."
            route: "/sa/SystemAdminHome/"
            methods:
              - GET
            function: SystemAdminHome
            roles:
              - systemAdmin
              
      - name: saChemTable
        handlers:
          # Chemical table controller
          - purpose: "Shows all Chemicals in Database."
            route: "/sa/ChemTable/"
            methods:
              - GET
            function: saChemTable
            roles:
              - systemAdmin
              
      - name: saViewChemical
        handlers:
        # Chemical page controller
          - purpose: "Shows specific chemical and all containers of said chemical."
            route: "/sa/ViewChemical/<string:chemical>/"
            methods:
              - GET
            function: saViewChemical
            roles:
              - systemAdmin
              
      - name: saCheckOut
        handlers:
          - purpose: "CheckOut a container"
            route: "/sa/CheckOut/"
            methods:
              - GET
              - POST
            function: saCheckOut
            roles:
              - systemAdmin
              
      - name: saCheckIn
        handlers:
          - purpose: "CheckIn a container"
            route: "/sa/CheckIn/"
            methods:
              - GET
              - POST
            function: saCheckIn
            roles:
              - systemAdmin
              
      - name: saCheckedOut
        handlers:
          - purpose: "Display containers that are checked out"
            route: "/sa/CheckedOut/"
            methods:
              - GET
            function: saCheckedOut
            roles:
              - systemAdmin
              
      - name: saAddChemical
        handlers:
          - purpose: "Add Chemical to the database"
            route: "/sa/AddChemical/"
            methods:
              - GET
              - POST
            function: saAddChemical
            roles:
              - systemAdmin
              
      - name: saAddContainer
        handlers:
          - purpose: "Add Container for a certain chemical"
            route: "/sa/AddContainer/"
            methods:
              - GET
              - POST
            function: saAddContainer
            roles:
              - systemAdmin
              
      - name: saCheckHistory
        handlers:
          - purpose: "Check history of a specific chemical"
            route: "/sa/CheckHistory/<string:chemical>/"
            methods:
              - GET
            function: saCheckHistory
            roles:
              - systemAdmin
              
################################################################################
    
  - directory:
    name: ma #LeslieKaylor
    controllers:
      - name: adminHome
        handlers :
          - purpose: "Dashboard and homepage for the Admin"
            route: "/ma/adminHome/"
            methods:
               - GET
            function: adminHome
            roles:
              - admin
      
      - name: UserAccess
        handlers :
          - purpose: "Approve and Deny Users"
            route: "/ma/UserAccess/"
            methods:
               - GET
               - POST
            function: UserAccess
            roles:
              - admin        
    
      - name: ViewUser
        handlers :
           - purpose: "View all the user and add new users "
             route: "/ma/ViewUser/"
             methods:
               - GET
               - POST
             function: ViewUser
             roles:
               - admin
               
      - name: ManageBuildings
        handlers:
           - purpose: "Edit, delete, and add buildings"
             route: "/ma/ManageBuildings/"
             methods:
               - GET
               - POST
             function: ManageBuildings
             roles:
               - admin
               
      - name: ManageFloors
        handlers:
           - purpose: "Edit, delete, and add floors and rooms"
             route: "/ma/ManageFloors/"
             methods:
               -  GET
               -  POST
             function: ManageFloors
             roles:
               - admin
               
      - name: maChemTable
        handlers:
          # Chemical table controller
          - purpose: "Shows all Chemicals in Database."
            route: "/ma/ChemTable/"
            methods:
              - GET
            function: maChemTable
            roles:
              - admin
              
      - name: maViewChemical
        handlers:
        # Chemical page controller
          - purpose: "Shows specific chemical and all containers of said chemical."
            route: "/ma/ViewChemical/<string:chemical>/"
            methods:
              - GET
            function: maViewChemical
            roles:
              - admin
              
      - name: maCheckOut
        handlers:
          - purpose: "CheckOut a container"
            route: "/ma/CheckOut/"
            methods:
              - GET
              - POST
            function: maCheckOut
            roles:
              - admin
              
      - name: maCheckIn
        handlers:
          - purpose: "CheckIn a container"
            route: "/ma/CheckIn/"
            methods:
              - GET
              - POST
            function: maCheckIn
            roles:
              - admin
              
      - name: maCheckedOut
        handlers:
          - purpose: "Display containers that are checked out"
            route: "/ma/CheckedOut/"
            methods:
              - GET
            function: maCheckedOut
            roles:
              - admin
              
      - name: maAddChemical
        handlers:
          - purpose: "Add Chemical to the database"
            route: "/ma/AddChemical/"
            methods:
              - GET
              - POST
            function: maAddChemical
            roles:
              - admin
              
      - name: maAddContainer
        handlers:
          - purpose: "Add Container for a certain chemical"
            route: "/ma/AddContainer/"
            methods:
              - GET
              - POST
            function: maAddContainer
            roles:
              - admin
              
      - name: maCheckHistory
        handlers:
          - purpose: "Check history of a specific chemical"
            route: "/ma/CheckHistory/<string:chemical>/"
            methods:
              - GET
            function: maCheckHistory
            roles:
              - admin