options: &units
  - measure: "Weight"
    units:
      - "gram (g)"
      - "kilogram (kg)"
      - "pound (lb)"
  - measure: "Volume"
    units:
      - "ounce (oz)"
      - "gallon (gal)"
      - "liter (L)"
      - "milliliter (mL)"
containerInformation:
    - name: "Checked Out"
      id: "checkedOut"
      type: "hidden"
      special: "noShow"
    - name: "Room"
      id: "storageId"
      type: "select"
      options: "roomsList"
      special: "required"
    - name: "Container Type"
      id: "conType"
      type: "select"
      options:
        - measure: ""
          units:
            - "Bottle"
            - "Jug"
            - "Drum"
            - "That's all I can think of right now"
    - name: "Current Quantity"
      id: "currentQuantity"
      type: "number"
      placeholder: "How much is currently in the container?"
      special: "required"
    - name: "Current Unit"
      id: "currentQuantityUnit"
      type: "select"
      options: *units
      special: "required"
    - name: "Container Capacity"
      id: "capacity"
      type: "number"
      placeholder: "How much can the container hold?"
      special: "required"
    - name: "Container Unit"
      id: "capacityUnit"
      type: "select"
      options: *units
      special: "required"
    - name: "Manufacturer"
      id: "manufacturer"
      type: "text"
      placeholder: "Manufacturer"
      special: "required"
    - name: "Barcode"
      id: "barcodeId"
      type: "hidden"
      special: "readonly"