Building:
    edit:
      - name: "Name"
        id: "name"
        type: "text"
      - name: "Number of Floors"
        id: "numFloors"
        type: "number"
      - name: "Address"
        id: "address"
        type: "text"
    delete:
        message: "Are you sure you want to delete this building?"
Floor:
    edit:
      - name: "Floor Number"
        id: "floorNum"
        type: "text"
      - name: "Storage Limits"
        id: "storageLimits"
        type: "text"
    delete:
        message: "Are you sure you want to delete this floor?"

Room:
    edit:
      - name: "Name"
        id: "name"
        type: "text"
    delete:
        message: "Are you sure you want to delete this room?"
        
Storage:
    edit:
      - name: "Name"
        id: "name"
        type: "text"
      - name: "Flammable"
        id: "flammable"
        type: "radio"
      - name: "Health Hazard"
        id: "healthHazard"
        type: "radio"
      - name: "Oxidizer"
        id: "oxidizer"
        type: "radio"
      - name: "Organic Acid"
        id: "orgAcid"
        type: "radio"
      - name: "Inorganic Acid"
        id: "inorgAcid"
        type: "radio"
      - name: "Base"
        id: "base"
        type: "radio"
      - name: "Peroxide"
        id: "peroxide"
        type: "radio"
      - name: "Pressure"
        id: "pressure"
        type: "radio"
    delete:
        message: "Are you sure you want to delete this Storage Location?"