# Only certain people can be admins in this app
admin:
  - ubuntu #For Testing
#  - database Roles

systemAdmin:
#   - ubuntu
  - group admin
  - AD systemAdmin

faculty:
  - group admin
  - AD faculty

systemUser:
#   - ubuntu
  - group faculty

anon:
  - ANY
