# Only certain people can be admins in this app
admin:
  - ubuntu #For Testing
  - ala_qasem
  - insengrim
  - ramsayb2
  - heggens
#  - database Roles

systemAdmin:
#   - ubuntu
  - group admin
  - AD systemAdmin

superUser:
#   - ubuntu
  - group admin
  - AD superUser

systemUser:
#   - ubuntu
  - group superUser

anon:
  - ANY
