# Only certain people can be admins in this app
admin:
  - heggens
  - jadudm
  - database Roles

students:
  - group admin
  - AD students

faculty:
  - group admin
  - AD faculty

withsuperpowers:
  - hunterr

valid:
  - group admin
  - group students
  - group faculty

anon:
  - ANY
