# Only certain people can be admins in this app
masterAdmin:
  - kaylorl
  - ubuntu #For Testing
  - database Roles

systemAdmin:
  - group admin
  - AD systemAdmin

faculty:
  - group admin
  - AD faculty

systemUser:
  - group masterAdmin
  - group systemAdmin
  - group faculty

anon:
  - ANY
