useraccess:
    - name: "User Name"
      id: "username"
      type: "text"
      placeholder: "username"
      special: "required"
      value: ""
      
    - name: "Report To"
      id: "reportto"
      type: "text"
      placeholder: "Supervisor's Name"
      special: "required"
      value: ""
      
    - name: "Email Address"
      id: "emailadd"
      type: "text"
      placeholder: "Email Address"
      special: "required"
      value: ""    
    
    - name: ""
      id: "auth_level"
      type: "hidden"
      placeholder: "Supervisor's Name"
      special: "required"
      value: "student"
      
    - name: ""
      id: "start_date"
      type: "hidden"
      placeholder: "Start Date"
      special: "required"
      value: ""
   
maaccess:
    - name: "User Name"
      id: "username"
      type: "text"
      placeholder: "username"
      special: "required"
      
    - name: "Report To"
      id: "reportto"
      type: "text"
      placeholder: "Supervisor's Name"
      special: "required"
      
    - name: ""
      id: "start_date"
      type: "hidden"
      placeholder: "Start Date"
      special: "required"
      
    - name: "Email Address"
      id: "emailadd"
      type: "text"
      placeholder: "Email Address"
      special: "required"
      
    - name: "Auth Level"
      id: "auth_level"
      type: "dropdown"
      placeholder: "Select One"
      special: &diffusers
        - "System Adminstrator"
        - "Faculty and Staff"
        - "Student"
    
        


    
      